#include "../../include/resources/local_resource.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ========================================================================= */
/* INTERNAL STRUCTURES                                                       */
/* ========================================================================= */

/**
 * @brief Represents a granted resource allocation for a specific remote node.
 * Instances of this structure are stored in the 'active_jobs_t' hash table.
 * The combination of 'job_id' and 'socket' serves as the unique primary key 
 * to prevent collisions between different nodes generating the same job_id.
 */
typedef struct{
    unsigned    job_id;             /**< Identifier generated by the remote Erlang scheduler */
    unsigned    socket;             /**< File descriptor representing the remote node connection */
    unsigned    resource_quantity;  /**< Amount of the resource that was granted */
    resource_t  resource_type;      /**< The specific hardware type (CPU, GPU, RAM) */
} elem_active_job_t;

/**
 * @brief Represents a pending request waiting for resources to become available.
 * Instances of this structure are stored in the FIFO queues. They hold the 
 * state of a reservation that could not be fulfilled immediately.
 */
typedef struct{
    unsigned    job_id;             /**< Identifier generated by the remote Erlang scheduler */
    unsigned    socket;             /**< File descriptor representing the remote node connection */
    unsigned    resource_quantity;  /**< Amount of the resource requested */
    resource_t  resource_type;      /**< The specific hardware type (CPU, GPU, RAM) */
} elem_job_request_t;

/**
 * @brief Temporary context passed through a void pointer during hash table traversal.
 * Used exclusively by 'free_all_resources_from_socket' to safely locate and collect 
 * all active jobs associated with a dead socket without relying on global variables.
 */
typedef struct {
    unsigned target_socket;             /**< The socket of the disconnected node we are looking for */
    elem_active_job_t ** to_delete;     /**< Array of pointers to collect the matches found */
    unsigned count;                     /**< Current number of matched elements found */
    unsigned max;                       /**< Maximum capacity of the 'to_delete' array */
} sweep_context_t;


/* ========================================================================= */
/* INTERNAL HELPERS - ACTIVE JOBS (HASH TABLE)                               */
/* ========================================================================= */

static void     dest_active_job     (elem_active_job_t * elem)                          { free(elem); }
static void * copy_active_job     (elem_active_job_t * elem)                          { return elem; }

// Compares both job_id and socket to ensure true unique identity across different Erlang clients
static int      comp_active_job     (elem_active_job_t * a, elem_active_job_t * b)      { 
    return (a -> job_id != b -> job_id || a -> socket != b -> socket || a -> resource_type != b -> resource_type); 
}

// Combines job_id and socket in the mathematical hash to avoid cluster collisions
static unsigned hash_active_job     (elem_active_job_t * elem)                          { 
    return ((elem -> job_id * 31) + elem -> socket) * RES_NUM + elem -> resource_type; 
}

// Internal constructor for creating a new active job element
static elem_active_job_t * create_elem_active_job( unsigned id, unsigned socket, unsigned quantity, resource_t type){
    elem_active_job_t * out = malloc(sizeof(elem_active_job_t));
    if(out == NULL) { return NULL; }

    out -> job_id               = id;
    out -> socket               = socket; 
    out -> resource_quantity    = quantity;
    out -> resource_type        = type;
    
    return out;
}

/**
 * [INTEGRATION] 
 * Where to call: Should be called ONLY ONCE during node initialization (e.g., inside 'node_init' in node-structures.c).
 */
active_jobs_t create_active_jobs_table(){
    return tablahash_crear(11, (FuncionCopiadora)copy_active_job, (FuncionComparadora)comp_active_job, (FuncionDestructora)dest_active_job, (FuncionHash)hash_active_job);
}


/* ========================================================================= */
/* INTERNAL HELPERS - PENDING JOB REQUESTS (QUEUES)                          */
/* ========================================================================= */

static void     dest_job_request    (elem_job_request_t * elem)                         { free(elem); }
static void * copy_job_request    (elem_job_request_t * elem)                         { return elem; }

// Standard comparator: Requires exact match of job_id, socket, and resource type
static int      comp_job_request    (elem_job_request_t * a, elem_job_request_t * b){ 
    return (a -> job_id != b -> job_id || a -> resource_type != b -> resource_type || a->socket != b->socket); 
}

// Custom comparator: Used by the GC to delete ALL requests from a specific socket, regardless of job_id
static int comp_job_request_by_socket (elem_job_request_t * a, unsigned * target_socket) { 
    return (a->socket != *target_socket); // Returns 0 (false) if sockets match, triggering the queue_delete
}

// Internal constructor for creating a new pending request element
static elem_job_request_t * create_job_request( unsigned id, unsigned socket, unsigned quantity, resource_t type){
    elem_job_request_t * out = malloc(sizeof(elem_job_request_t));
    if(out == NULL) { return NULL; }

    out -> job_id               = id;
    out -> socket               = socket;
    out -> resource_quantity    = quantity;
    out -> resource_type        = type;

    return out;
}


/* ========================================================================= */
/* PHYSICAL INVENTORY MANAGEMENT                                             */
/* ========================================================================= */

/**
 * [INTEGRATION] 
 * Where to call: Should be called ONLY ONCE during node initialization (e.g., inside 'node_init')
 * to define the physical hardware boundaries of this specific node.
 */
local_resources_t * create_local_resource( unsigned cpu,  unsigned gpu,  unsigned ram){
    local_resources_t * out = malloc(sizeof(local_resources_t));
    if (out == NULL) return NULL;
    
    out -> total[CPU] = cpu;
    out -> total[GPU] = gpu;
    out -> total[RAM] = ram;
    
    for( unsigned t = 0 ; t < RES_NUM ; t++) { 
        out -> avail[t] = out -> total[t]; 
        out -> request_queue[t] = queue_create(); 
    }

    return out;
}

/**
 * [INTEGRATION] 
 * Where to call: Should be called during graceful shutdown (e.g., inside 'node_dest')
 * to free the main structure and all pending elements in the queues to prevent memory leaks.
 */
void delete_local_resource(local_resources_t * resources){
    if (resources == NULL) return;
    
    for (unsigned idx = 0 ; idx < RES_NUM ; idx++) { 
        queue_destroy(resources -> request_queue[idx], (FuncionDestructora)dest_job_request); 
    }
    free(resources);
}


/* ========================================================================= */
/* RESERVATIONS & WAITING QUEUE LOGIC                                        */
/* ========================================================================= */

/**
 * [INTEGRATION]
 * Where to call: Inside the Patcher (resource_adapter.c) when parsing a CMD_RESERVE.
 * Example: int result = new_job_request(NODE->resources, NODE->active_jobs, job_id, socket, quantity, type);
 * If result == -1 -> send DENIED.
 * If result == 1  -> send GRANTED.
 * If result == 0  -> Do nothing (it is queued).
 */
int new_job_request (local_resources_t * resources, active_jobs_t active_jobs, unsigned id, unsigned socket, unsigned quantity, resource_t type){
    
    // 1. HARD REJECT: Request exceeds the maximum physical capacity of the machine.
    if (quantity > resources->total[type]) {
        return -1; 
    }

    // 2. QUEUE: Valid request, but not enough resources currently available. Enqueue it.
    if(resources -> avail[type] < quantity){
        elem_job_request_t * new = create_job_request(id, socket, quantity, type);
        if(new != NULL)
            resources -> request_queue[type] = queue_add(resources -> request_queue[type], new, (FuncionCopiadora)copy_job_request);
        return 0; 
    }
    
    // 3. IMMEDIATE GRANT: Resources available. Deduct inventory and track the active job.
    resources -> avail[type] -= quantity;
    tablahash_insertar(active_jobs, create_elem_active_job(id, socket, quantity, type));

    return 1; 
}

/**
 * [INTEGRATION]
 * Where to call: Inside the Patcher (resource_adapter.c) IMMEDIATELY AFTER freeing resources 
 * (after a CMD_RELEASE or an ACTION_DISCONNECTED) to check if any queued node can now be served.
 * Important: This should be called in a while loop until it returns -1, as freeing 
 * a large chunk of resources might fulfill multiple smaller queued requests.
 */
int chk_job_request (local_resources_t * resources, active_jobs_t active_jobs, char * OUT, unsigned OUT_SIZE, unsigned *out_socket){
    queue_t                 act         = NULL;
    elem_job_request_t  * act_elem    = NULL;
    int out = -1;    
    
    // Randomize the starting resource type to prevent starvation of a specific queue
    resource_t init = rand() % RES_NUM;
    resource_t type;

    for(resource_t idx = 0; idx < RES_NUM && out == -1 ; idx++){
        type = (init + idx) % RES_NUM;
        act = resources -> request_queue[type];
        
        do{ 
            if(queue_empty(act)) { break; }

            act_elem = act -> data;

            // If still not enough resources for this specific request, skip it and check the next one
            if(resources -> avail[type] < act_elem -> resource_quantity) { 
                act = act -> next; 
                continue; 
            }

            // Resources found! Fulfill the request, deduct inventory, and track the job
            resources -> avail[type] -= act_elem -> resource_quantity;
            out = act_elem -> job_id;

            if (out_socket != NULL)
                *out_socket = act_elem -> socket;

            tablahash_insertar(active_jobs, create_elem_active_job(act_elem -> job_id, act_elem->socket, act_elem ->resource_quantity, type));

            // Remove it from the waiting queue
            resources -> request_queue[type] = queue_delete(resources -> request_queue[type], act_elem, (FuncionDestructora)dest_job_request, (FuncionComparadora)comp_job_request);

            break; // Exit the queue traversal since we fulfilled one request
        }while(act != NULL);
    }

    if (out != -1) {
        snprintf(OUT, OUT_SIZE, "GRANTED %d\n", out);
    }

    return out;
}


/* ========================================================================= */
/* RESOURCE RELEASE LOGIC                                                    */
/* ========================================================================= */

/**
 * [INTEGRATION]
 * Where to call: Inside the Patcher (resource_adapter.c) when handling a CMD_RELEASE.
 * This restores the specific physical resources to the node's available pool.
 */
void del_active_job (local_resources_t * resources, active_jobs_t jobs, unsigned job_id, unsigned socket){
    for (resource_t type = 0; type < RES_NUM; type++) {
        // Create a dummy element using the composite key (job_id + socket) to find it
        elem_active_job_t * dummy = create_elem_active_job(job_id, socket, 0, type);
        if(dummy == NULL) return;

        elem_active_job_t * job_actual = tablahash_buscar(jobs, dummy);

        if(job_actual != NULL) {
            // Restore inventory
            resources->avail[job_actual -> resource_type] += job_actual -> resource_quantity;
            tablahash_eliminar(jobs, dummy);
        }

        dest_active_job(dummy);
    }
}

/**
 * [INTEGRATION]
 * Where to call: Inside the Patcher (resource_adapter.c) when handling a CMD_RELEASE 
 * or CMD_JOB_RELEASE, to remove requests that were queued but are now being aborted by the client.
 */
void del_pending_job_requests(local_resources_t * resources, unsigned job_id, unsigned socket){
    for (resource_t type = 0; type < RES_NUM; type++) {
        queue_t act = resources -> request_queue[type];

        while (!queue_empty(act)) {
            elem_job_request_t * elem = act -> data;

            // Strict match required to avoid deleting someone else's request with the same job_id
            if (elem -> job_id == job_id && elem->socket == socket) {
                resources -> request_queue[type] = queue_delete(
                    resources -> request_queue[type],
                    elem,
                    (FuncionDestructora)dest_job_request,
                    (FuncionComparadora)comp_job_request
                );
                act = resources -> request_queue[type]; // Reset iterator after structural modification
            } else {
                act = act -> next;
            }
        }
    }
}

// Visitor function used internally by free_all_resources_from_socket to scan the hash table
static void check_dead_socket(void * dato, void * extra) {
    elem_active_job_t * job = (elem_active_job_t *)dato;
    sweep_context_t * ctx = (sweep_context_t *)extra;

    if (job->socket == ctx->target_socket && ctx->count < ctx->max) {
        ctx->to_delete[ctx->count++] = job;
    }
}

/**
 * [INTEGRATION]
 * Where to call: Inside the Patcher (resource_adapter.c) strictly during an ACTION_DISCONNECTED event.
 * This is the Garbage Collector function that prevents deadlocks when a remote node crashes.
 */
void free_all_resources_from_socket(local_resources_t * resources, active_jobs_t jobs, unsigned socket) {
    
    // --- PHASE A: Purge ACTIVE JOBS (Resources currently held hostage by the dead node) ---
    sweep_context_t ctx;
    ctx.target_socket = socket;
    ctx.count = 0;
    ctx.max = 100; // Assumption: A single node won't hold more than 100 concurrent resource chunks
    ctx.to_delete = malloc(sizeof(elem_active_job_t *) * ctx.max);
    
    if (ctx.to_delete != NULL) {
        // We pass 'ctx' by reference. The visitor will populate ctx.to_delete with the findings.
        tablahash_visitar_extra(jobs, check_dead_socket, &ctx);
        
        for (unsigned i = 0; i < ctx.count; i++) {
            elem_active_job_t * dead_job = ctx.to_delete[i];
            
            // Reclaim resources to the local pool
            resources->avail[dead_job->resource_type] += dead_job->resource_quantity;
            tablahash_eliminar(jobs, dead_job);
        }
        free(ctx.to_delete);
    }

    // --- PHASE B: Purge PENDING JOBS (Requests clogging the queues from the dead node) ---
    for (resource_t type = 0; type < RES_NUM; type++) {
        queue_t act = resources->request_queue[type];

        while (!queue_empty(act)) {
            elem_job_request_t * elem = act->data;

            if (elem->socket == socket) {
                // Delete using the native queue function, but using our custom socket-only comparator
                resources->request_queue[type] = queue_delete(
                    resources->request_queue[type],
                    &socket, // Passed as reference to be used by 'comp_job_request_by_socket'
                    (FuncionDestructora)dest_job_request,
                    (FuncionComparadora)comp_job_request_by_socket
                );
                // Restart traversal from the head of the queue since elements shifted
                act = resources->request_queue[type]; 
            } else {
                act = act->next;
            }
        }
    }
}


/* ========================================================================= */
/* QUERIES AND DATA EXTRACTION                                               */
/* ========================================================================= */

/**
 * [INTEGRATION]
 * Where to call: Inside the Patcher (resource_adapter.c) when preparing to broadcast 
 * a CMD_ANNOUNCE via UDP, or when formatting a GET_NODES response.
 */
void get_local_resources(local_resources_t * resources, unsigned * cpu_quantity, unsigned * gpu_quantity, unsigned * mem_quantity){
    if(cpu_quantity) { * cpu_quantity = resources -> avail[CPU]; }    
    if(gpu_quantity) { * gpu_quantity = resources -> avail[GPU]; }
    if(mem_quantity) { * mem_quantity = resources -> avail[RAM]; }    
}