#include "../../include/resources/owned_jobs.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ========================================================================= */
/* INTERNAL STRUCTURES                                                       */
/* ========================================================================= */

/**
 * @brief Represents a single resource request sent to a specific remote node.
 * Contained within the array of an elem_owned_job_t.
 */
typedef struct {
    char * ip;                  /**< Target node's IP address */
    unsigned port;              /**< Target node's TCP port */
    resource_t type;            /**< Type of resource requested */
    unsigned quantity;          /**< Amount of resource requested */
    int is_granted;             /**< State flag: 0 = Pending/Sent, 1 = GRANTED received */
} job_petition_t;

/**
 * @brief Represents a complete job initiated by the local Erlang scheduler.
 * Stored in the 'owned_jobs_t' hash table.
 */
typedef struct {
    unsigned job_id;                /**< Unique identifier from Erlang */
    unsigned owner_socket;
    int grant_notified;             /**< Flag to ensure Erlang is notified only once when completed */
    time_t created_at;              /**< Timestamp for garbage collection (timeouts) */
    
    unsigned petition_count;        /**< Total number of nodes involved in this job */
    unsigned next_reserve_idx;      /**< Index of the next RESERVE request to be dispatched */
    
    /**< Array preserving the exact strict order of the Erlang requests */
    job_petition_t petitions[MAX_JOB_RESOURCES]; 
} elem_owned_job_t;


/* ========================================================================= */
/* HASH TABLE INTERNAL HELPERS                                               */
/* ========================================================================= */

static char * strduplicate(const char *s){
    size_t len = strlen(s) + 1;
    char *p = malloc(len);
    if(p) memcpy(p, s, len);
    return p;
}

static void dest_owned_job(elem_owned_job_t * elem){
    if(elem == NULL) return;
    // Free the dynamically allocated strings inside the petitions array
    for (unsigned i = 0; i < elem->petition_count; i++) {
        free(elem->petitions[i].ip);
    }
    free(elem);
}

static void * copy_owned_job (elem_owned_job_t * elem) { return elem; }

// Equality is based solely on the unique job_id generated by Erlang
static int comp_owned_job (elem_owned_job_t * a, elem_owned_job_t * b) { return a->job_id != b->job_id; } 

static unsigned hash_owned_job (elem_owned_job_t * elem) { return elem->job_id; }


/* ========================================================================= */
/* INITIALIZATION & DESTRUCTION                                              */
/* ========================================================================= */

owned_jobs_t create_owned_jobs() {
    return tablahash_crear(11, (FuncionCopiadora)copy_owned_job, (FuncionComparadora)comp_owned_job, (FuncionDestructora)dest_owned_job, (FuncionHash)hash_owned_job);
}

void delete_owned_jobs(owned_jobs_t jobs) { 
    tablahash_destruir(jobs); 
}


/* ========================================================================= */
/* JOB CONSTRUCTION (POPULATING FROM ERLANG)                                 */
/* ========================================================================= */

int add_new_owned_job(owned_jobs_t jobs, unsigned job_id, unsigned owner_socket) {
    elem_owned_job_t * new_job = malloc(sizeof(elem_owned_job_t));
    if (!new_job) return 0;

    new_job->job_id = job_id;
    new_job->owner_socket = owner_socket;
    new_job->grant_notified = 0;
    new_job->created_at = time(NULL);
    new_job->petition_count = 0;
    new_job->next_reserve_idx = 0;

    tablahash_insertar(jobs, new_job);
    return 1;
}

unsigned get_job_owner_socket(owned_jobs_t jobs, unsigned job_id) {
    elem_owned_job_t dummy = { .job_id = job_id };
    elem_owned_job_t * job = tablahash_buscar(jobs, &dummy);
    return job ? job->owner_socket : 0;
}

int append_petition_to_job(owned_jobs_t jobs, unsigned job_id, const char * ip, unsigned port, resource_t type, unsigned quantity) {
    // Create a dummy struct just to leverage the hash table search function
    elem_owned_job_t dummy = { .job_id = job_id };
    elem_owned_job_t * job = tablahash_buscar(jobs, &dummy);
    
    if (!job || job->petition_count >= MAX_JOB_RESOURCES) return 0;

    // Append to the contiguous array
    unsigned idx = job->petition_count;
    job->petitions[idx].ip = strduplicate(ip);
    job->petitions[idx].port = port;
    job->petitions[idx].type = type;
    job->petitions[idx].quantity = quantity;
    job->petitions[idx].is_granted = 0; // State machine starts at 0
    
    job->petition_count++;
    return 1;
}


/* ========================================================================= */
/* NETWORK STATE UPDATES (HANDLING REMOTE RESPONSES)                         */
/* ========================================================================= */

int mark_petition_as_granted(owned_jobs_t jobs, unsigned job_id, const char * ip, unsigned port) {
    elem_owned_job_t dummy = { .job_id = job_id };
    elem_owned_job_t * job = tablahash_buscar(jobs, &dummy);
    if (!job || job->next_reserve_idx == 0) return -1;

    unsigned idx = job->next_reserve_idx - 1;
    if (job->petitions[idx].port != port || strcmp(job->petitions[idx].ip, ip) != 0) return -1;
    if (job->petitions[idx].is_granted) return -1;

    job->petitions[idx].is_granted = 1;

    int all_granted = 1;
    for (unsigned i = 0; i < job->petition_count; i++) {
        if (!job->petitions[i].is_granted) {
            all_granted = 0;
            break;
        }
    }

    if (all_granted && !job->grant_notified) {
        job->grant_notified = 1;
        return 1;
    }
    
    return 0;
}


/* ========================================================================= */
/* OUTBOX BUILDERS (EXTRACTING DATA FOR NETWORK TRANSMISSION)                */
/* ========================================================================= */

int get_next_reserve(owned_jobs_t jobs, unsigned job_id, char ** out_ip, unsigned * out_port, resource_t * out_type, unsigned * out_quantity) {
    elem_owned_job_t dummy = { .job_id = job_id };
    elem_owned_job_t * job = tablahash_buscar(jobs, &dummy);
    
    // If job doesn't exist or we already sent RESERVE messages to all nodes
    if (!job || job->next_reserve_idx >= job->petition_count) return 0;

    unsigned idx = job->next_reserve_idx;
    *out_ip = job->petitions[idx].ip;
    *out_port = job->petitions[idx].port;
    *out_type = job->petitions[idx].type;
    *out_quantity = job->petitions[idx].quantity;
    
    job->next_reserve_idx++; // Advance the pointer for the next call
    return 1;
}

unsigned get_granted_resources(owned_jobs_t jobs, unsigned job_id, char * arr_ip[], unsigned arr_port[], resource_t arr_type[], unsigned arr_quantity[], unsigned max_size) {
    elem_owned_job_t dummy = { .job_id = job_id };
    elem_owned_job_t * job = tablahash_buscar(jobs, &dummy);
    if (!job) return 0;

    unsigned count = 0;
    
    // Iterate ONLY up to the requests we actually dispatched to the network
    for (unsigned i = 0; i < job->next_reserve_idx && count < max_size; i++) {
        // Filter: Extract ONLY the ones that actively gave us resources
        if (job->petitions[i].is_granted == 1) {
            arr_ip[count] = job->petitions[i].ip;
            arr_port[count] = job->petitions[i].port;
            arr_type[count] = job->petitions[i].type;
            arr_quantity[count] = job->petitions[i].quantity;
            count++;
        }
    }
    return count;
}

void remove_owned_job(owned_jobs_t jobs, unsigned job_id) {
    elem_owned_job_t dummy = { .job_id = job_id };
    tablahash_eliminar(jobs, &dummy); // Will trigger dest_owned_job internally
}


/* ========================================================================= */
/* FAULT TOLERANCE AND GARBAGE COLLECTION                                    */
/* ========================================================================= */

/**
 * @brief Temporary context for the dead node visitor. 
 * Allows safely passing search parameters into the hash table traversal.
 */
typedef struct {
    const char * dead_ip;
    unsigned dead_port;
    unsigned * affected_jobs;
    unsigned count;
    unsigned max;
} dead_node_ctx_t;

// Visitor function executed for each job in the hash table
static void check_job_for_dead_node(void * dato, void * extra) {
    elem_owned_job_t * job = (elem_owned_job_t *)dato;
    dead_node_ctx_t * ctx = (dead_node_ctx_t *)extra;

    if (ctx->count >= ctx->max) return;

    // Scan all petitions within this specific job
    for (unsigned i = 0; i < job->petition_count; i++) {
        // If this job was interacting with the crashed node
        if (job->petitions[i].port == ctx->dead_port && strcmp(job->petitions[i].ip, ctx->dead_ip) == 0) {
            // Register this job as ruined (entire job must be aborted)
            ctx->affected_jobs[ctx->count] = job->job_id;
            ctx->count++;
            return; 
        }
    }
}

unsigned get_jobs_affected_by_dead_node(owned_jobs_t jobs, const char * dead_ip, unsigned dead_port, unsigned affected_job_ids[], unsigned max_size) {
    // Pack the search parameters into the context
    dead_node_ctx_t ctx = {dead_ip, dead_port, affected_job_ids, 0, max_size};
    
    // Leverage the custom visitor (from tablahash.h) to avoid global variables
    tablahash_visitar_extra(jobs, check_job_for_dead_node, &ctx);
    
    return ctx.count;
}


/* --- TIMEOUT MANAGEMENT --- */

/**
 * @brief Temporary context for the timeout visitor. 
 */
typedef struct {
    unsigned * timeout_job_ids;
    unsigned count;
    unsigned max;
    time_t now;
} timeout_ctx_t;

static void check_timeout_job(void * dato, void * extra) {
    elem_owned_job_t * job = (elem_owned_job_t *)dato;
    timeout_ctx_t * ctx = (timeout_ctx_t *)extra;

    if (ctx->count >= ctx->max) return;
    
    // If the job is already fully granted, it cannot timeout
    if (job->grant_notified) return; 

    // Calculate time elapsed since the job was requested
    if (difftime(ctx->now, job->created_at) > JOB_TIMEOUT) {
        ctx->timeout_job_ids[ctx->count] = job->job_id;
        ctx->count++;
    }
}

unsigned collect_timed_out_jobs(owned_jobs_t jobs, unsigned job_ids[], unsigned max_size) {
    timeout_ctx_t ctx = {job_ids, 0, max_size, time(NULL)};
    tablahash_visitar_extra(jobs, check_timeout_job, &ctx);
    return ctx.count;
}

/* ========================================================================= */
/* ORPHANED CLIENT CLEANUP (HEADLESS NODE RECOVERY)                          */
/* ========================================================================= */

/**
 * @brief Temporary context for the orphaned jobs visitor.
 * Safely passes search parameters into the hash table traversal.
 */
typedef struct {
    unsigned dead_socket;
    unsigned * orphaned_jobs;
    unsigned count;
    unsigned max;
} orphan_ctx_t;

// Visitor function executed for each job in the hash table
static void check_orphaned_jobs(void * dato, void * extra) {
    elem_owned_job_t * job = (elem_owned_job_t *)dato;
    orphan_ctx_t * ctx = (orphan_ctx_t *)extra;

    // Abort if we reach the maximum array size
    if (ctx->count >= ctx->max) return;

    // If this job was requested by the Erlang client that just died
    if (job->owner_socket == ctx->dead_socket) {
        ctx->orphaned_jobs[ctx->count] = job->job_id;
        ctx->count++;
    }
}

unsigned get_jobs_by_owner_socket(owned_jobs_t jobs, unsigned socket, unsigned orphaned_job_ids[], unsigned max_size) {
    // Pack the search parameters into the context
    orphan_ctx_t ctx = {socket, orphaned_job_ids, 0, max_size};
    
    // Leverage the custom visitor to avoid global variables (Thread-Safe)
    tablahash_visitar_extra(jobs, check_orphaned_jobs, &ctx);
    
    return ctx.count;
}