#ifndef OWNED_JOBS_H
#define OWNED_JOBS_H

#include "tablahash.h"
#include "common_types.h"

#define MAX_JOB_RESOURCES 50
#define JOB_TIMEOUT 20

/**
 * @brief Hash table representing the jobs generated by the local Erlang scheduler.
 */
typedef TablaHash owned_jobs_t;


/* ========================================================================= */
/* CREATION AND DESTRUCTION                                                  */
/* ========================================================================= */

/**
 * @brief Initializes the manager for jobs owned by the local Erlang client.
 * @return A new empty hash table.
 */
owned_jobs_t create_owned_jobs();

/**
 * @brief Frees the memory allocated for the owned jobs manager.
 * @param jobs Pointer to the hash table to destroy.
 */
void delete_owned_jobs(owned_jobs_t jobs);


/* ========================================================================= */
/* JOB CONSTRUCTION (CALLED DURING JOB_REQUEST PARSING)                      */
/* ========================================================================= */

/**
 * @brief Registers a new job initiated by the local Erlang scheduler.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher when parsing the beginning of a CMD_JOB_REQUEST.
 * * @param jobs Hash table managing the owned jobs.
 * @param job_id The unique identifier generated by the Erlang scheduler.
 * @return 1 on success, 0 on memory allocation failure.
 */
int add_new_owned_job(owned_jobs_t jobs, unsigned job_id, unsigned owner_socket);
unsigned get_job_owner_socket(owned_jobs_t jobs, unsigned job_id);

/**
 * @brief Appends a single resource request to an existing job.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher, within a loop, while parsing the "@ip:port:res:amount" 
 * tokens of a CMD_JOB_REQUEST.
 * * @param jobs Hash table managing the owned jobs.
 * @param job_id The unique identifier of the job.
 * @param ip The IP address of the remote node to request resources from.
 * @param port The TCP port of the remote node.
 * @param type The type of resource requested (CPU, GPU, RAM).
 * @param quantity The amount of the resource requested.
 * @return 1 on success, 0 if the job was not found or maximum petitions reached.
 */
int append_petition_to_job(owned_jobs_t jobs, unsigned job_id, const char * ip, unsigned port, resource_t type, unsigned quantity);


/* ========================================================================= */
/* NETWORK STATE UPDATES                                                     */
/* ========================================================================= */

/**
 * @brief Marks a specific resource request as granted after receiving a response from a remote node.
 * It also checks if all petitions for this job are now fulfilled.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher when receiving a CMD_GRANTED from a remote node.
 * * @param jobs Hash table managing the owned jobs.
 * @param job_id The identifier of the job that received the grant.
 * @param ip The IP of the remote node that granted the resource.
 * @param port The port of the remote node that granted the resource.
 * @return 1 if the job is complete, 0 if it remains pending, -1 if the response does not match.
 */
int mark_petition_as_granted(owned_jobs_t jobs, unsigned job_id, const char * ip, unsigned port);


/* ========================================================================= */
/* OUTBOX BUILDERS (ITERATORS FOR NETWORK MESSAGES)                          */
/* ========================================================================= */

/**
 * @brief Retrieves the next pending resource request that needs to be sent across the network.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher to build a CMD_RESERVE message. Call this right after 
 * parsing a JOB_REQUEST, and also right after receiving a GRANTED (if the job is not yet fully completed).
 * * @param jobs Hash table managing the owned jobs.
 * @param job_id The identifier of the job.
 * @param out_ip Pointer to retrieve the target IP.
 * @param out_port Pointer to retrieve the target port.
 * @param out_type Pointer to retrieve the resource type to request.
 * @param out_quantity Pointer to retrieve the amount to request.
 * @return 1 if there is a next reserve to send, 0 if all reserves have been dispatched.
 */
int get_next_reserve(owned_jobs_t jobs, unsigned job_id, char ** out_ip, unsigned * out_port, resource_t * out_type, unsigned * out_quantity);

/**
 * @brief Retrieves ONLY the resources that have been successfully granted so far.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher when a job needs to be aborted (e.g., received a CMD_DENIED 
 * or a node crashed). Used to build CMD_RELEASE messages for the surviving nodes.
 * * @param jobs Hash table managing the owned jobs.
 * @param job_id The identifier of the job.
 * @param arr_ip Array to populate with target IPs.
 * @param arr_port Array to populate with target ports.
 * @param arr_type Array to populate with resource types.
 * @param arr_quantity Array to populate with resource quantities.
 * @param max_size The maximum capacity of the provided arrays.
 * @return The number of granted resources extracted.
 */
unsigned get_granted_resources(owned_jobs_t jobs, unsigned job_id, char * arr_ip[], unsigned arr_port[], resource_t arr_type[], unsigned arr_quantity[], unsigned max_size);


/* ========================================================================= */
/* FAULT TOLERANCE AND GARBAGE COLLECTION                                    */
/* ========================================================================= */

/**
 * @brief Scans all owned jobs to find which ones were requesting or holding resources 
 * from a node that abruptly disconnected.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher during an ACTION_CHECK_DEADNODES event, right after 
 * the known_nodes GC reports a dead IP and Port.
 * * @param jobs Hash table managing the owned jobs.
 * @param dead_ip The IP of the disconnected node.
 * @param dead_port The port of the disconnected node.
 * @param affected_job_ids Array to populate with the IDs of the ruined jobs.
 * @param max_size The maximum capacity of the array.
 * @return The number of affected jobs found.
 */
unsigned get_jobs_affected_by_dead_node(owned_jobs_t jobs, const char * dead_ip, unsigned dead_port, unsigned affected_job_ids[], unsigned max_size);

/**
 * @brief Scans all owned jobs to find which ones have stalled waiting for a network response.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher periodically (e.g., triggered by a timerfd) during an ACTION_CHECK_DEADNODES.
 * * @param jobs Hash table managing the owned jobs.
 * @param job_ids Array to populate with the IDs of the timed-out jobs.
 * @param max_size The maximum capacity of the array.
 * @return The number of timed-out jobs found.
 */
unsigned collect_timed_out_jobs(owned_jobs_t jobs, unsigned job_ids[], unsigned max_size);

/**
 * @brief Permanently removes a job from the local tracking system.
 * * [INTEGRATION]
 * Where to call: Inside the Patcher when a job successfully finishes (CMD_JOB_RELEASE), 
 * or when a job fails entirely (CMD_DENIED or timeout/node crash).
 * * @param jobs Hash table managing the owned jobs.
 * @param job_id The identifier of the job to remove.
 */
void remove_owned_job(owned_jobs_t jobs, unsigned job_id);

/**
 * @brief Retrieves all job IDs owned by a specific socket.
 * Used for garbage collection when a local Erlang client crashes 
 * or disconnects unexpectedly, leaving orphaned transactions.
 * * @param jobs The hash table containing all owned jobs.
 * @param socket The file descriptor of the disconnected client.
 * @param orphaned_job_ids Array to store the found orphaned job IDs.
 * @param max_size Maximum capacity of the array to prevent buffer overflows.
 * @return unsigned The number of orphaned jobs found.
 */
unsigned get_jobs_by_owner_socket(owned_jobs_t jobs, unsigned socket, unsigned orphaned_job_ids[], unsigned max_size);

#endif
